# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Define the server VM
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
    
    # Customize resources
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

    # Provisioning with shell script
    server.vm.provision "shell", path: "server_provision.sh"
  end

  # Define the database VM
  config.vm.define "database" do |database|
    database.vm.box = "ubuntu/focal64"
    database.vm.hostname = "database"
    database.vm.network "private_network", ip: "192.168.56.11"
    
    # Customize resources
    database.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end

    # Provisioning with shell script
    database.vm.provision "shell", path: "database_provision.sh"
  end
end

